# Generated by Django 5.1 on 2024-08-26 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="tag",
            new_name="label",
        ),
        migrations.AlterField(
            model_name="issue",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "To Do"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FINISHED", "Finished"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="issue",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
